<a href="https://colab.research.google.com/github/kittimaxz/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #packege สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (ที่อยู่ในรูปแบบ Matrix)

# Numpy Array

## สร้าง numpy array (matrix)

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape # ใช้ดูขนาด

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])

In [6]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (zeros,ones)

In [8]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np_200 = 200* np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random

In [11]:
np.random.randn(5,5) # random เลขมาจาก normal disttribution  ที่มี mu = 0,std = 1

array([[-0.12691235,  0.28046655, -0.33411468,  0.92251366, -2.8515614 ],
       [ 0.84598566, -0.73417262,  0.64073175, -0.60107718,  0.90415028],
       [ 0.44083398, -0.15322572,  1.07237859, -0.07477539,  0.52080768],
       [ 1.34414783,  1.05417143, -0.25885294,  0.49629338, -0.61515398],
       [ 0.33422278, -1.84449424, -0.31094116,  1.59967002,  0.4750751 ]])

In [12]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal disttribution  ที่มี mu = 2,std = 5

array([[ 0.39912827,  7.75486572,  4.40232863],
       [ 3.78460021,  3.23421928,  7.28941936],
       [ 3.43469311, -0.32964689, -2.80948692]])

In [13]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็มม ระหว่าง [5,11) ขนาด (4x5)

array([[ 5,  6, 10,  7,  6],
       [ 8, 10,  7,  6, 10],
       [ 5,  8,  6,  9,  5],
       [ 5,  5,  9,  5,  5]])

## Matrix transpose

In [14]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np_a.T # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
1 + np_a # adding scalar to matrix #บวก 1 เข้าทุกตัวของเมทริกซ์

array([[2, 3, 4],
       [5, 6, 7]])

In [16]:
2 * np_a # multipling scalar to matrix #คูณ 2 เข้าทุกตัวของเมทริกซ์

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
np_c = np.array([[6,5,4],[3,2,1]])

In [18]:
np_a + np_c # adding matrix to matrix  # เมทริกจะบวกกันโดยใช้เลขที่ตรงกัน

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
np_a.shape #ดูขนาด

(2, 3)

In [20]:
np_c.shape

(2, 3)

In [21]:
np.dot(np_a,np_c) # multipling matrix to matrix (a,b) x (b,c) # คูณกันไม่ได้เพราะมีขนาดที่ไม่เท่ากัน

ValueError: ignored

In [22]:
np_c.T

array([[6, 3],
       [5, 2],
       [4, 1]])

In [23]:
np.dot(np_a,np_c.T)

array([[28, 10],
       [73, 28]])

# Indexing & Slicing

In [24]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np_a[1,1]

5

In [26]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [27]:
np_a[0,:]

array([1, 2, 3])

# Useful functions

In [29]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.sum(np_a) # การรวมทุกเลข

21

In [30]:
np.sum(np_a,axis=0) # axis 0 ก็คือรวมเลขในแต่ละแถว # เป็นการเอาค่าในแนวแกนนอนมารวมกัน

array([5, 7, 9])

In [31]:
np.sum(np_a,axis=1) # axis 1 ก็คือรวมเลขในแต่ละหลัก # เป็นการเอาค่าในแนวแกนตั้งมารวมกัน

array([ 6, 15])

In [32]:
np.mean(np_a)

3.5

In [34]:
np.mean(np_a,axis=0) # หาค่า mean ของ column

array([2.5, 3.5, 4.5])

## วนลูปเอง

### Summation



```
np.sum(np_a)
```



In [37]:
sum_all = 0

for row in range(np_a.shape[0]) : 
    for col in range(np_a.shape[1]) :
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row = {row}, col = {col}, np_a[{row},{col}] = {np_a[row,col]}, sum_all = {sum_all}')
print(sum_all)

we are at row = 0, col = 0, np_a[0,0] = 1, sum_all = 1
we are at row = 0, col = 1, np_a[0,1] = 2, sum_all = 3
we are at row = 0, col = 2, np_a[0,2] = 3, sum_all = 6
we are at row = 1, col = 0, np_a[1,0] = 4, sum_all = 10
we are at row = 1, col = 1, np_a[1,1] = 5, sum_all = 15
we are at row = 1, col = 2, np_a[1,2] = 6, sum_all = 21
21




```
np.sum(axis=0)
```



In [38]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]) : 
    for col in range(np_a.shape[1]) :
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


# Quiz กลุ่ม

วนลูปหาค่า

* np.sum(np_a,axis=1)
* np.mean(np_a)
* np.mean(np_a,axis=0)
* np.mean(np_a,axis=1)

In [39]:
sum_all = np.zeros(np_a.shape[0])

for row in range(np_a.shape[0]) : 
    for col in range(np_a.shape[1]) :
        sum_all[row] = sum_all[row] + np_a[row,col]
print(sum_all)

[ 6. 15.]
