<a href="https://colab.research.google.com/github/kittimaxz/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #packege สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (ที่อยู่ในรูปแบบ Matrix)

# Numpy Array

## สร้าง numpy array (matrix)

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape # ใช้ดูขนาด

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])

In [7]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## Matrix transpose

In [8]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (zeros,ones)

In [9]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np_200 = 200* np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random

In [13]:
np.random.randn(5,5) # random เลขมาจาก normal disttribution  ที่มี mu = 0,std = 1

array([[-0.02817344,  0.54885236, -0.68266078, -1.51186687, -0.66283167],
       [ 0.1045079 ,  1.53815343, -0.88487115,  0.34965574,  1.05522124],
       [ 1.29850594,  0.06196927, -0.44249992, -1.05592091,  0.67276055],
       [-1.10253107, -0.25417548, -2.20532151,  0.69547153,  0.49178742],
       [-1.74636392, -1.37707491, -1.41413053,  1.81536846, -0.63255064]])

In [16]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal disttribution  ที่มี mu = 2,std = 5

array([[ 0.3320266 ,  3.44177383,  5.76823329],
       [-0.24734451, -2.16850643, -6.16146593],
       [ 1.58465231, -0.59782933,  8.07358636]])

In [17]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็มม ระหว่าง [5,11) ขนาด (4x5)

array([[ 9,  5,  9,  7, 10],
       [ 7, 10,  8, 10,  8],
       [ 6, 10,  7,  5,  7],
       [ 5,  7,  9,  5,  6]])